const Service = require('../ServiceHistory/Service')
const service = new Service();
const config = require('./ApiRun');
const moment = require('moment')

export async function ServiceHistory() {
  // 接続確認用URL
  var url = config.getDomain() + '/Sodan/v1/syukei/kensu?pHostname=PC01&pJigyoid=43&pTaisyo=1&pSymd=20220301&pEymd=20220331&pSiid=0&pChiku=0';
  // テスト用
  var url = "/";
  var uniqid = 1;
  config.setURL(url);
  config.setUniqID(uniqid);

  return await service.getData().then(result => {
    // 利用者情報一覧
    let icrn_inf = [];    
    icrn_inf.push({
      serviceTeikyoJigyosyoCode: 1001,
      serviceTeikyoJigyosyo: '０１２３４５６７８９０１２３４５６７８９',
      serviceCode: 22,
      serviceMeisyo: '０１２３４５６７８９０１２３４５',
      riyocode: 1234567,
      names: '０１２３４５６７８９',
      kana: 'タロウトウケイ',
      gender: '男',
      genderKey: '1',
      birth: moment('19300615').format('YYYY/MM/DD'),
      age: 30,
      spice: '',
      startDate: moment('20230401').format('YYYY/MM/DD'),
      endDate: '',
      useYear: 0,
      useMonth: 4,
    }, {
      serviceTeikyoJigyosyoCode: 1001,
      serviceTeikyoJigyosyo: '障害者支援施設 ひまわり園',
      serviceCode: 22,
      serviceMeisyo: '生活介護',
      riyocode: 10000002,
      names: '東経 花子',
      kana: 'ハナコトウケイ',
      gender: '女',
      genderKey: '2',
      birth: moment('19820505').format('YYYY/MM/DD'),
      age: 30,
      spice: '',
      startDate: moment('20200901').format('YYYY/MM/DD'),
      endDate: '',
      useYear: 1,
      useMonth: 11,
    }, {
      serviceTeikyoJigyosyoCode: 1001,
      serviceTeikyoJigyosyo: '障害者支援施設 ひまわり園',
      serviceCode: 22,
      serviceMeisyo: '生活介護',
      riyocode: 10000003,
      names: '東経 二郎',
      kana: 'ジロウトウケイ',
      gender: '男',
      genderKey: '1',
      birth: moment('19820505').format('YYYY/MM/DD'),
      age: 30,
      spice: '',
      startDate: moment('20181115').format('YYYY/MM/DD'),
      endDate: '',
      useYear: 3,
      useMonth: 8,
    }, {
      serviceTeikyoJigyosyoCode: 1001,
      serviceTeikyoJigyosyo: '障害者支援施設 ひまわり園',
      serviceCode: 32,
      serviceMeisyo: '施設入所支援',
      riyocode: 10000001,
      names: '東経 太郎',
      kana: 'タロウトウケイ',
      gender: '男',
      genderKey: '1',
      birth: moment('19300615').format('YYYY/MM/DD'),
      age: 30,
      spice: '',
      startDate: moment('20210401').format('YYYY/MM/DD'),
      endDate: '',
      useYear: 0,
      useMonth: 4,
    }, {
      serviceTeikyoJigyosyoCode: 1001,
      serviceTeikyoJigyosyo: '障害者支援施設 ひまわり園',
      serviceCode: 32,
      serviceMeisyo: '施設入所支援',
      riyocode: 10000002,
      names: '東経 花子',
      kana: 'ハナコトウケイ',
      gender: '女',
      genderKey: '2',
      birth: moment('19300209').format('YYYY/MM/DD'),
      age: 30,
      spice: '',
      startDate: moment('20200901').format('YYYY/MM/DD'),
      endDate: '',
      useYear: 1,
      useMonth: 11,
    }, {
      serviceTeikyoJigyosyoCode: 1001,
      serviceTeikyoJigyosyo: '障害者支援施設 ひまわり園',
      serviceCode: 32,
      serviceMeisyo: '施設入所支援',
      riyocode: 10000003,
      names: '東経 ジロウ',
      kana: 'ジロウトウケイ',
      gender: '',
      genderKey: '',
      birth: '',
      age: '',
      spice: '',
      startDate: moment('20181105').format('YYYY/MM/DD'),
      endDate: '',
      useYear: 3,
      useMonth: 8,
    }, {
      serviceTeikyoJigyosyoCode: 1002,
      serviceTeikyoJigyosyo: '自立訓練事業所 たんぽぽ園',
      serviceCode: 41,
      serviceMeisyo: '自立訓練(機能訓練)',
      riyocode: 10000004,
      names: '東経 三郎',
      kana: 'サブロウトウケイ',
      gender: '男',
      genderKey: '1',
      birth: moment('19790602').format('YYYY/MM/DD'),
      age: '36',
      spice: '',
      startDate: moment('20190210').format('YYYY/MM/DD'),
      endDate: '',
      useYear: 2,
      useMonth: 5,
    }, {
      serviceTeikyoJigyosyoCode: 1002,
      serviceTeikyoJigyosyo: '自立訓練事業所 たんぽぽ園',
      serviceCode: 41,
      serviceMeisyo: '自立訓練(機能訓練)',
      riyocode: 10000005,
      names: '東経 明日香',
      kana: 'アスカトウケイ',
      gender: '女',
      genderKey: '2',
      birth: moment('20080301').format('YYYY/MM/DD'),
      age: '23',
      spice: '',
      startDate: moment('20191220').format('YYYY/MM/DD'),
      endDate: '',
      useYear: 1,
      useMonth: 7,
    }, {
      serviceTeikyoJigyosyoCode: '',
      serviceTeikyoJigyosyo: '',
      serviceCode: null,
      serviceMeisyo: '',
      riyocode: 10000006,
      names: '東経 うみか',
      kana: 'ウミカトウケイ',
      gender: '女',
      genderKey: '2',
      birth: moment('19911215').format('YYYY/MM/DD'),
      age: '32',
      spice: '通',
      startDate: '',
      endDate: '',
      useYear: 0,
      useMonth: 0,
    }, {
      serviceTeikyoJigyosyoCode: '',
      serviceTeikyoJigyosyo: '',
      serviceCode: null,
      serviceMeisyo: '',
      riyocode: 10000009,
      names: '西経 五郎',
      kana: 'ゴロウニシケイ',
      gender: '男',
      genderKey: '1',
      birth: moment('19870501').format('YYYY/MM/DD'),
      age: '30',
      spice: '',
      startDate: '',
      endDate: '',
      useYear: 0,
      useMonth: 0,
    }, {
      serviceTeikyoJigyosyoCode: '',
      serviceTeikyoJigyosyo: '',
      serviceCode: null,
      serviceMeisyo: '',
      riyocode: 10000011,
      names: '西経 みどり',
      kana: 'ミドリニシケイ',
      gender: '女',
      genderKey: '2',
      birth: moment('19800818').format('YYYY/MM/DD'),
      age: '41',
      spice: '',
      startDate: '',
      endDate: '',
      useYear: 0,
      useMonth: 0,
    }, {
      serviceTeikyoJigyosyoCode: '',
      serviceTeikyoJigyosyo: '',
      serviceCode: null,
      serviceMeisyo: '',
      riyocode: 10000015,
      names: '西経 桃子',
      kana: 'モモコニシケイ',
      gender: '女',
      genderKey: '2',
      birth: moment('19900901').format('YYYY/MM/DD'),
      age: '29',
      spice: '',
      startDate: '',
      endDate: '',
      useYear: 0,
      useMonth: 0,
    });

    // 日付を合わせる処理
    for (let i = 0; i < icrn_inf.length; i++) {
      icrn_inf[i].processTime = icrn_inf[i].useYear + "-" + icrn_inf[i].useMonth;
    }
    let returns = {
      status:1,
      icrn_inf: icrn_inf,
    };
    return returns;

  });


}